homework/homework/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('author/', include("authors.urls")),
    path('tag/', include("tags.urls")),
    path('users/', include("users.urls")),

]

homework/tags/urls.py
from django.urls import path
from . import views

app_name = 'tags'

urlpatterns = [
    path('', views.main, name = "root"),
    path("<tag>", views.main, name = "main"),
    path('toptentags/', views.toptentags, name='toptentags'),
]

homework/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('addauthor/', views.addauthor, name='addauthor'),
    path('addquote/', views.addquote, name='addquote'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

homework/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)
            

homework/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, CharField, TextInput, DateInput
from quotes.models import Author, Quote
from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    email = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())
    class Meta:
        model = Profile
        fields = ['avatar']


class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=55, required=True, widget=TextInput())
    born_date = CharField(min_length=5, max_length=25, required=True, widget=DateInput())
    born_location = CharField(min_length=5, max_length=65, required=True, widget=TextInput())
    description = CharField(min_length=10,   required=True, widget=forms.Textarea(attrs={'rows': 10}))
    class Meta:
        model = Author
        fields = ['fullname','born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    quote = CharField(min_length=10,   required=True, widget=forms.Textarea(attrs={'rows': 3}))
    tags = CharField(min_length=1, max_length=25, required=True, widget=TextInput())
    author = CharField(min_length=2, max_length=65, required=True, widget=TextInput())
    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['tags', 'author']




    

homework/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm, LoginForm, AuthorForm, QuoteForm
from quotes.models import Tag, Author
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:root')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:root')


@login_required
def addquote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():

            new_quote = form.save(commit=False)  # Відкладено збереження 

            # Перевіряємо, чи був обраний автор
            author_name = request.POST.get("author")
            if author_name:
                chosen_author = Author.objects.get(fullname=author_name)
                new_quote.author = chosen_author

            new_quote.save()  # Зберігаємо цитату

            # Додаємо теги до нової цитати
            chosen_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
            for tag in chosen_tags:
                new_quote.tags.add(tag)

            return redirect(to='quotes:root')
        else:
            return render(request, 'users/addquote.html', {'authors': authors, 'tags': tags, 'form': form})
    return render(request, 'users/addquote.html', context={'authors': authors, 'tags': tags, "form": QuoteForm()})


@login_required
def addauthor(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/addauthor.html', {'form': form})
    return render(request, 'users/addauthor.html', context={"form": AuthorForm()})


@login_required
def profile(request):
    return render(request, 'users/profile.html')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

homework/users/templates/users/addauthor.html
{% extends "quotes/base.html" %} {% block content %}

<div>
  <h2>Author adding</h2>
</div>

{% if messages %}
<div>
  {% for message in messages %}
  <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:addauthor' %}" method="post">
  {% csrf_token %}
  <div>
    <label> Author fullname: {{ form.fullname }} </label>
  </div>

  <div>
    <label>Author born date: {{ form.born_date }} </label>
  </div>

  <div>
    <label>Author born location: {{ form.born_location }} </label>
  </div>

  <div>
    <label>Author description: {{ form.description }} </label>
  </div>

  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% endblock content %}

homework/users/templates/users/addquote.html
{% extends "quotes/base.html" %} {% block content %}

<div>
  <h2>Quote adding</h2>
</div>


<form method="POST" action="{% url 'users:addquote' %}">
    {% csrf_token %}

    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>

    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div style="padding: 10px">
        <label> Select author:
            <select name="author" required>
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>


{% endblock content %}

homework/users/templates/users/login.html
{% extends "quotes/base.html" %}
{% block content %}

<div>
    <h2>Login</h2>
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username: {{ form.username }} </label>
    </div>

    <div>
        <label>Password: {{ form.password }} </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

    <div class="small text-center">
        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
    </div>

</form>

{% endblock %}

homework/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

homework/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset complete!</h2>

{% endblock %}

homework/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

homework/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

homework/users/templates/users/password_reset_email.html
{% autoescape off %}

<body>
    <p>Hi {{ user.username }},</p>
    <p>You requested a password reset for your account. Please follow this link to set a new password:</p>
    <p>
        <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
            {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
        </a>
    </p>
    <p>If you didn't request a password reset, please ignore this email.</p>
    <p>Thanks,</p>
    <p>The Our Team</p>
    {% endautoescape %}

homework/users/templates/users/profile.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h1>Profile page: {{user.username}}</h1>
    <img src="{{ user.profile.avatar.url }}" alt="avatar of user" />
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-5">
            <div class="form-group">
                <label class="small mb-1">Change Avatar:</label>
                {{ profile_form.avatar }}
                <span>{{ profile_form.errors.avatar }}</span>
            </div>
        </div>
    </div>
    <div class="grid">
        <button type="submit">Save Changes</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>

{% endblock content %}

homework/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}