homework/homework/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('author/', include("authors.urls")),
    path('tag/', include("tags.urls")),
    path('users/', include("users.urls")),

]

homework/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name = "root"),
    path('page/<int:page>', views.main, name = "root_paginate"),
]

homework/tags/urls.py
from django.urls import path
from . import views

app_name = 'tags'

urlpatterns = [
    path('', views.main, name = "root"),
    path("<tag>", views.main, name = "main"),
    path('toptentags/', views.toptentags, name='toptentags'),
]

homework/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('addauthor/', views.addauthor, name='addauthor'),
    path('addquote/', views.addquote, name='addquote'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

homework/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    ctreated_at = models.DateField(auto_now_add=True)
    
    def __str__ (self):
        return f"{self.fullname}"

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False)
    
    def __str__ (self):
        return f"{self.name}"
   

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE,  null=False)
    ctreated_at = models.DateField(auto_now_add=True)
    
    

homework/quotes/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Quote


def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, "quotes/index.html", context = {"quotes" : quotes_on_page} )

homework/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="veiwport" />
  <title>Homework10</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
  {%load static %}
  <link rel="stylesheet" href="{% static 'quotes/style.css' %}" />
</head>

<body>
  <div class="container">
    <div class="row header-box pt-4 mb-4">
      <h1>
        <a href="/" style="text-decoration: none">Quotes to Scrape</a>
      </h1>
      <div class="col-md-4">
        <nav style="margin-bottom: 30px; border-bottom: 3px solid; padding-left: 30px">
          {% if user.is_authenticated %}
          <ul>
            <h2> Welcome <b>{{ user.username }}! </b> </h2>
              <a href="{% url 'users:logout' %}" type="button" class="btn btn-danger btn-sm login" >Logout</a> 
          </ul>

          <ul class="btn-group" role="group" >
              <a href="{% url 'users:addauthor' %}" role="button" type="button" class="btn btn-outline-success btn-sm" >Add Author</a>
              <a href="{% url 'users:addquote' %}"  role="button" type="button" class="btn btn-outline-success btn-sm" >Add Quote</a>
          </ul>

          {% else %}
          <ul class=" login">
            <a href="{% url 'users:signup' %}" type="button" class="btn btn-success btn-sm">SignUp</a>
            <a href="{% url 'users:login' %}"  type="button" class="btn btn-success btn-sm"  >Login</a>
          </ul>
          {% endif %}
        </nav>
      </div>
    </div>

    {% block content%} {% endblock %}
  </div>

</body>

</html>

homework/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}

{% load extract %}
{% block content %}

<div class="row">
  <div class="col-md-8">
    {%for quote in quotes%}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text"> {{quote.quote}} </span>
      <span>by
        <small class="author" itemprop="author">
          {{quote.author.fullname}}
        </small>
        <a href="/author/{{quote.author.fullname}}">(about)</a>
      </span>
      <div class="tags">
        Tags:
        {%for tag in quote.id|tags %}
        <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
        {%endfor%}
      </div>
    </div>
    {%endfor%}

    <nav>
      <ul class="pager">
        <li class="previous">
          <a class="{% if not quotes.has_previous %} disabled {% endif %}"
           href="{% if quotes.has_previous %} {% url "quotes:root_paginate" quotes.previous_page_number %} {% else %} # {% endif %}">
            <span aria-hidden="true">←</span> Previous</a>
        </li>
        <li class="next">
           <a class="{% if not quotes.has_next %} disabled {% endif %}"
           href="{% if quotes.has_next %} {% url "quotes:root_paginate" quotes.next_page_number %} {% else %} # {% endif %}">
           Next <span aria-hidden="true">→</span></a>
        </li>
      </ul>
    </nav>

    <div class="container10">
      <div class="tags-box">
              <a  href="{% url 'tags:toptentags' %}" style="text-decoration: none"><h1> TopTenTags</h1></a>
              {%for tag in toptags|toptags%}  
              <div  itemscope="" itemtype="http://schema.org/CreativeWork">
                <li>
                  <span class="text" itemprop="text" style="font-weight: bold">
                    <a class="tag" style="font-size: {{ tag.quote_count|add:tag.quote_count }}px" href="/tag/{{ tag.name }}" role="button">{{ tag.name }}</a>
                </li>
              </div>
              {%endfor%}
      </div>
   </div>
{% endblock %}